# Multiple app config
DEVELOPMENT: &dev
    APP_NAME: 'zeus'
    APP_TYPE: 'bottle'
    APP_BASE: 'bottle'
    CLIENT_ID: 7131
    CLIENT_SECRET: '55df5dde98eb34acb6b0b306a0b200fa'
    MODULE: 'zeus:app'
    DEBUG: true

STAGING:
    <<: *dev

PRODUCTION:
    <<: *dev
    DEBUG: false
    MAIL_DEBUG: false
